# Generated by Django 5.2.5 on 2025-08-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVAnalyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Adresse email (identifiant de connexion)', max_length=254, unique=True),
        ),
    ]
