# Generated by Django 5.2.5 on 2025-08-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVAnalyzer', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text="Nom d'utilisateur généré automatiquement", max_length=150, unique=True),
        ),
    ]
