# Generated by Django 5.2.5 on 2025-08-29 08:08

import CVAnalyzer.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVAnalyzer', '0002_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(help_text='Intitulé du poste', max_length=200)),
                ('entreprise', models.CharField(blank=True, help_text="Nom de l'entreprise", max_length=200)),
                ('cv', models.FileField(help_text='CV au format PDF, DOC ou DOCX', upload_to=CVAnalyzer.models.upload_cv_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('lettre_motivation', models.FileField(blank=True, help_text='Lettre de motivation (optionnelle)', null=True, upload_to=CVAnalyzer.models.upload_lettre_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', "En cours d'examen"), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='en_attente', help_text='Statut de la candidature', max_length=20)),
                ('score_ia', models.FloatField(blank=True, help_text="Score d'analyse IA (0-100)", null=True)),
                ('competences_extraites', models.JSONField(blank=True, default=list, help_text='Compétences extraites par IA')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commentaires', models.TextField(blank=True, help_text='Commentaires du recruteur')),
                ('candidat', models.ForeignKey(help_text='Candidat qui postule', on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
                'ordering': ['-created_at'],
            },
        ),
    ]
