# Generated by Django 5.2.5 on 2025-08-29 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CVAnalyzer', '0003_alter_user_username'),
        ('CVAnalyzer', '0003_candidature'),
    ]

    operations = [
    ]
