# Generated by Django 5.2.5 on 2025-08-29 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CVAnalyzer', '0004_merge_0003_alter_user_username_0003_candidature'),
    ]

    operations = [
    ]
